### ISSUE TITLE
Identify AI aircraft and ignore them

### ISSUE THREAD

**Issue by Bankler** [magwo/dcs-comms-plan-enforcer#3]
Would be nice to have short declarative (white) notes on AI aircraft, instead of outputting the warning about a radio that is "not checkable". It should be possible to identify if a unit is AI by checking if the skill is anything else than client or player, and if so, you skip it, with an output in the style of:
_FA-18C_hornet Blue Singleton Easy: AI_
or similar.
![image](https://user-images.githubusercontent.com/25781776/127854884-a97f1e62-6779-4b89-b0c0-ff6c4c0dac54.png)

json-content for a non AI unit looks like this.
["skill"] = "Client"
(can also be "Player")

**Comment by magwo** [comment]
Fixed by https://github.com/magwo/dcs-comms-plan-enforcer/commit/3ba89d3ce93fae254d8f6d01cde67b05e767a0f9
